@extends('frontend.layouts.app')
@section('content')
    <div class="page-banner">
        <div class="page-banner-content">
            <div class="container">
                <h1 class="page-banner-title text-center">Terms And Conditions</h1>
                {{-- <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Terms And Conditions</li>
                    </ol>
                </nav> --}}
            </div>
        </div>
    </div>

    <div class="our-gallery mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12 col-md-10 text-center">
                    {{-- <h2 class="gallery-title text-center mt-4"><strong>Terms And Conditions</strong></h2> --}}
                </div>
            </div>
            <div class="tab-content mt-5" id="pills-tabContent">
                <div class="terms-and-onditions">
                    <h1 class="card-title mb-3">Terms of Use</h1>
                    <p class="legal-header">This document is an electronic record in terms of the Information Technology
                        Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic
                        records in various statutes as amended by the Information Technology Act, 2000. This electronic
                        record is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <hr>
                    <section id="introduction" class="mb-4">
                        <p class="small-note">Published in accordance with Rule 3(1) of the Information Technology
                            (Intermediaries Guidelines) Rules, 2011.</p>


                        <p>The Platform (www.canntumemporium.com) including the related mobile site and mobile application
                            (together, the "Platform") is owned and operated by <strong>Canntum.</strong></p>


                        <address>
                            {{-- <strong>CANNTUM OFFICE</strong><br>
                        379(B), Crosscut road,<br>
                        Gandhipuram, Coimbatore,<br>
                        Tamil Nadu, 641012
                    </address> --}}


                            <p>Throughout these Terms of Use, references to "Platform Owner", "we", "us" or "our" shall mean
                                Canntum. References to "you", "your" or "user" shall mean any natural or legal person who
                                accesses or uses the Platform.</p>
                    </section>


                    <h5 class="section-title">Agreement to Terms</h5>
                    <p>By accessing, browsing or otherwise using the Platform, you indicate your agreement to be bound by
                        these Terms of Use ("Terms"). If you transact on the Platform, you will also be subject to the
                        applicable policies which are incorporated herein by reference.</p>


                    <h5 class="section-title mt-4">Use of the Platform</h5>
                    <ul>
                        <li>You agree to provide true, accurate and complete information during registration and to be
                            responsible for all activity that occurs under your account.</li>
                        <li>Neither we nor third parties warrant the accuracy, timeliness, performance, completeness or
                            suitability of information on the Platform. You accept that content may contain inaccuracies and
                            we exclude liability for such inaccuracies to the fullest extent permitted by law.</li>
                        <li>Your use of the Platform and Services is at your own risk. You should independently assess
                            whether the Services meet your requirements.</li>
                    </ul>


                    <h5 class="section-title mt-4">Intellectual Property</h5>
                    <p>All content on the Platform (including design, layout, look and graphics) is proprietary and licensed
                        to the Platform Owner. You will not acquire any intellectual property rights in the content.</p>


                    <h5 class="section-title mt-4">Prohibited Uses</h5>
                    <p>You agree not to use the Platform for any unlawful purpose or in violation of these Terms or
                        applicable Indian laws.</p>


                    <h5 class="section-title mt-4">External Links</h5>
                    <p>The Platform may contain links to third-party websites. Use of such links will be governed by the
                        third-party's terms and policies. We provide such links only for convenience.</p>


                    <h5 class="section-title mt-4">Transactions</h5>
                    <p>By initiating a transaction on the Platform, you enter into a legally binding contract with the
                        Platform Owner for the Services ordered. You agree to pay the charges applicable to such Services.
                    </p>


                    <h5 class="section-title mt-4">Indemnity</h5>
                    <p>You shall indemnify and hold harmless the Platform Owner, its affiliates, officers, directors, agents
                        and employees from any claims, demands, liabilities, losses, damages, costs and expenses (including
                        reasonable attorneys' fees) arising out of your breach of these Terms or violation of applicable
                        laws or third-party rights (including IP infringement).</p>


                </div>
            </div>
        </div>
    </div>
@endsection
